// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN0Drq3YtXe4hbrYFd1RhFlKl3xUkXFFY',
    appId: '1:928693290794:web:49d840cc50b5e6801d8053',
    messagingSenderId: '928693290794',
    projectId: 'dhav-quick-commerce',
    authDomain: 'dhav-quick-commerce.firebaseapp.com',
    databaseURL: 'https://dhav-quick-commerce-default-rtdb.firebaseio.com',
    storageBucket: 'dhav-quick-commerce.firebasestorage.app',
    measurementId: 'G-LBTNR16C6F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs1cO1oZnbV-Se2UvppIQbSsUj3O0zW6s',
    appId: '1:928693290794:android:121337c5366f24151d8053',
    messagingSenderId: '928693290794',
    projectId: 'dhav-quick-commerce',
    databaseURL: 'https://dhav-quick-commerce-default-rtdb.firebaseio.com',
    storageBucket: 'dhav-quick-commerce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArgkUQz__kh13ZW6bpCy2OlCvn9jx0QQ0',
    appId: '1:928693290794:ios:36bd25e23bd9d70b1d8053',
    messagingSenderId: '928693290794',
    projectId: 'dhav-quick-commerce',
    databaseURL: 'https://dhav-quick-commerce-default-rtdb.firebaseio.com',
    storageBucket: 'dhav-quick-commerce.firebasestorage.app',
    iosClientId: '928693290794-qc8579fdfl74qabaqvkv4kq0r8vesi04.apps.googleusercontent.com',
    iosBundleId: 'com.dhav.storeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDN0Drq3YtXe4hbrYFd1RhFlKl3xUkXFFY',
    appId: '1:928693290794:web:a411b06bc30466031d8053',
    messagingSenderId: '928693290794',
    projectId: 'dhav-quick-commerce',
    authDomain: 'dhav-quick-commerce.firebaseapp.com',
    databaseURL: 'https://dhav-quick-commerce-default-rtdb.firebaseio.com',
    storageBucket: 'dhav-quick-commerce.firebasestorage.app',
    measurementId: 'G-GQ4F28B90J',
  );
}
