-- ============================================================================
-- DHAV — FULL DATABASE SCHEMA (single source of truth, current state)
-- ============================================================================
-- This ONE file recreates the ENTIRE schema as it exists today. It already
-- includes every column added by later migrations, so it is equivalent to
-- running 001 + 003 + 004 together.
--
-- USE THIS WHEN:  you wiped the database (test mode) and want everything back.
--   1. Run THIS file  (creates all tables + indexes)
--   2. Run 005_seed_marketplace.sql  (fills the 4 marketplaces with demo data)
--   That's it — you do NOT also need 001 / 003 / 004 (they're folded in here).
--
-- Everything is IF NOT EXISTS / ADD COLUMN IF NOT EXISTS, so running it on a DB
-- that already has these tables is harmless (it just fills any gaps).
--
-- Conventions:
--   • TEXT primary keys (UUID strings generated by the app via new_id()).
--   • Timestamps are BIGINT epoch-milliseconds.
--   • marketplace_type / store_type ∈ ('grocery','fruits','electronics','pharmacy').
-- ============================================================================


-- ── users ───────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS users (
    uid               TEXT PRIMARY KEY,            -- Firebase UID
    phone             TEXT,
    name              TEXT,
    email             TEXT,
    fcm_token         TEXT,
    address           JSONB,                       -- default delivery address
    saved_addresses   JSONB DEFAULT '[]',          -- list of saved address objects
    role              TEXT DEFAULT 'customer',     -- customer | store_owner | delivery | admin
    store_id          TEXT,                        -- set when role = store_owner
    language          TEXT DEFAULT 'en',
    is_active         BOOLEAN DEFAULT true,
    created_at        BIGINT DEFAULT 0             -- epoch ms
);


-- ── stores ──────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS stores (
    id                   TEXT PRIMARY KEY,
    owner_uid            TEXT,
    owner_name           TEXT,
    shop_name            TEXT,
    name                 TEXT,                     -- alias used in admin onboard flow
    store_type           TEXT DEFAULT 'grocery',   -- grocery|fruits|electronics|pharmacy (which marketplace)
    area                 TEXT,
    phone                TEXT,
    email                TEXT,
    address              TEXT,
    geohash6             TEXT,                     -- geohash precision-6 of store location
    location             JSONB,                    -- {lat, lng, geohash}
    is_open              BOOLEAN DEFAULT false,
    is_active            BOOLEAN DEFAULT true,
    is_verified          BOOLEAN DEFAULT false,
    is_suspended         BOOLEAN DEFAULT false,
    strike_count         INT DEFAULT 0,
    total_strikes        INT DEFAULT 0,
    suspension_end_date  BIGINT,
    available_item_ids   JSONB DEFAULT '[]',
    total_orders_accepted INT DEFAULT 0,
    total_orders_failed  INT DEFAULT 0,
    onboarded_by         TEXT,
    rating               FLOAT DEFAULT 0.0,
    fcm_token            TEXT,
    operating_hours      JSONB,
    self_delivery        BOOLEAN DEFAULT false,    -- owner delivers own orders (shares live GPS)
    image_url            TEXT DEFAULT '',
    onboarding_date      BIGINT,
    inventory            JSONB DEFAULT '{}',       -- {item_id: {qty, is_available}}
    updated_at           BIGINT,
    deleted_at           BIGINT,
    created_at           BIGINT DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_stores_geohash ON stores(geohash6);
CREATE INDEX IF NOT EXISTS idx_stores_owner   ON stores(owner_uid);
CREATE INDEX IF NOT EXISTS idx_stores_active  ON stores(is_active, is_open, is_verified);
CREATE INDEX IF NOT EXISTS idx_stores_type    ON stores(store_type);


-- ── catalog_items (master product catalog, marketplace-aware) ────────────────
CREATE TABLE IF NOT EXISTS catalog_items (
    id               TEXT PRIMARY KEY,
    name             TEXT NOT NULL,
    name_hindi       TEXT DEFAULT '',
    name_marathi     TEXT DEFAULT '',
    category         TEXT,                          -- legacy free-text category label
    marketplace_type TEXT DEFAULT 'grocery',        -- grocery|fruits|electronics|pharmacy
    category_id      TEXT,                          -- FK → categories.id
    subcategory_id   TEXT,                          -- FK → subcategories.id
    brand            TEXT DEFAULT '',
    sku              TEXT DEFAULT '',
    description      TEXT DEFAULT '',
    price            FLOAT DEFAULT 0,               -- sale price
    mrp              FLOAT DEFAULT 0,               -- struck-through MRP
    discount_percent FLOAT DEFAULT 0,               -- % OFF
    stock_quantity   INT DEFAULT 0,
    unit             TEXT,
    is_active        BOOLEAN DEFAULT true,
    image_url        TEXT DEFAULT '',               -- primary image (list cards)
    images           JSONB DEFAULT '[]',            -- 3-5 image URLs (detail carousel)
    specs            JSONB DEFAULT '{}',            -- key→value: RAM/Storage/Battery/Warranty / nutrition / healthcare
    group_id         TEXT,                          -- SKU family: unit-variants (10kg/5kg/1kg) share this
    rating           FLOAT DEFAULT 0,               -- avg product rating
    rating_count     INT   DEFAULT 0,               -- number of ratings
    created_at       BIGINT DEFAULT 0,
    updated_at       BIGINT
);

CREATE INDEX IF NOT EXISTS idx_catalog_active      ON catalog_items(is_active);
CREATE INDEX IF NOT EXISTS idx_catalog_category    ON catalog_items(category);
CREATE INDEX IF NOT EXISTS idx_catalog_marketplace ON catalog_items(marketplace_type);
CREATE INDEX IF NOT EXISTS idx_catalog_category_id ON catalog_items(category_id);
CREATE INDEX IF NOT EXISTS idx_catalog_subcategory ON catalog_items(subcategory_id);
CREATE INDEX IF NOT EXISTS idx_catalog_group       ON catalog_items(group_id);


-- ── categories (admin-managed, DB-driven taxonomy) ──────────────────────────
CREATE TABLE IF NOT EXISTS categories (
    id               TEXT PRIMARY KEY,
    marketplace_type TEXT NOT NULL DEFAULT 'grocery',
    name             TEXT NOT NULL,
    image_url        TEXT DEFAULT '',
    sort_order       INT  DEFAULT 0,
    is_enabled       BOOLEAN DEFAULT true,
    created_at       BIGINT DEFAULT 0,
    updated_at       BIGINT
);

CREATE INDEX IF NOT EXISTS idx_categories_market  ON categories(marketplace_type, sort_order);
CREATE INDEX IF NOT EXISTS idx_categories_enabled ON categories(is_enabled);


-- ── subcategories (admin-managed, parent = categories.id) ───────────────────
CREATE TABLE IF NOT EXISTS subcategories (
    id               TEXT PRIMARY KEY,
    category_id      TEXT NOT NULL,
    marketplace_type TEXT NOT NULL DEFAULT 'grocery',
    name             TEXT NOT NULL,
    image_url        TEXT DEFAULT '',
    sort_order       INT  DEFAULT 0,
    is_enabled       BOOLEAN DEFAULT true,
    created_at       BIGINT DEFAULT 0,
    updated_at       BIGINT
);

CREATE INDEX IF NOT EXISTS idx_subcategories_cat     ON subcategories(category_id, sort_order);
CREATE INDEX IF NOT EXISTS idx_subcategories_market  ON subcategories(marketplace_type);
CREATE INDEX IF NOT EXISTS idx_subcategories_enabled ON subcategories(is_enabled);


-- ── marketplaces (admin-configurable verticals; DB-driven tabs/theme) ────────
CREATE TABLE IF NOT EXISTS marketplaces (
    wire                TEXT PRIMARY KEY,          -- marketplace_type value
    name                TEXT NOT NULL,
    tab_label           TEXT DEFAULT '',
    emoji               TEXT DEFAULT '🛍️',
    color_primary       TEXT DEFAULT '',
    color_primary_dark  TEXT DEFAULT '',
    color_accent        TEXT DEFAULT '',
    color_header_top    TEXT DEFAULT '',
    color_header_bottom TEXT DEFAULT '',
    color_tint          TEXT DEFAULT '',
    sort_order          INT  DEFAULT 0,
    is_enabled          BOOLEAN DEFAULT true,
    created_at          BIGINT DEFAULT 0,
    updated_at          BIGINT
);

CREATE INDEX IF NOT EXISTS idx_marketplaces_order ON marketplaces(sort_order);

-- Seed the original 4 verticals (idempotent) — see 008_marketplaces.sql.
INSERT INTO marketplaces
    (wire, name, tab_label, emoji, color_primary, color_primary_dark, color_accent,
     color_header_top, color_header_bottom, color_tint, sort_order, is_enabled,
     created_at, updated_at) VALUES
('grocery','DHAV','DHAV','🛍️','#1E88E5','#1565C0','#42A5F5','#2196F3','#1565C0','#E3F2FD',0,true,1718900000000,1718900000000),
('fruits','Fresh Fruits','Fresh Fruits','🍉','#2E7D32','#1B5E20','#43A047','#43A047','#2E7D32','#E8F5E9',1,true,1718900000000,1718900000000),
('electronics','Electronics','Electronics','🎧','#1A237E','#0D1551','#3949AB','#3949AB','#1A237E','#E8EAF6',2,true,1718900000000,1718900000000),
('pharmacy','Pharmacy','Pharmacy','💊','#00897B','#00695C','#00ACC1','#00ACC1','#00897B','#E0F2F1',3,true,1718900000000,1718900000000)
ON CONFLICT (wire) DO NOTHING;


-- ── orders ──────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS orders (
    id                       TEXT PRIMARY KEY,
    order_id                 TEXT,               -- same as id, for JSON response compatibility
    customer_id              TEXT,
    accepted_by_store_id     TEXT,
    assigned_delivery_boy_id TEXT,
    delivery_boy_name        TEXT,
    delivery_boy_phone       TEXT,
    status                   TEXT DEFAULT 'pending',
    marketplace_type         TEXT DEFAULT 'grocery',  -- drives type-correct broadcast routing
    items                    JSONB DEFAULT '[]',
    customer_address         JSONB,
    total_product_amount     FLOAT DEFAULT 0,
    delivery_fee             FLOAT DEFAULT 0,
    total_customer_amount    FLOAT DEFAULT 0,
    platform_fee_percentage  FLOAT DEFAULT 5.0,
    platform_fee_amount      FLOAT DEFAULT 0,
    platform_fee_settled     BOOLEAN DEFAULT false,
    payment_method           TEXT DEFAULT 'cod',
    broadcast_wave           INT DEFAULT 0,
    broadcast_radius_km      FLOAT DEFAULT 0,
    broadcast_store_ids      JSONB DEFAULT '[]',
    rejected_store_ids       JSONB DEFAULT '[]',
    timed_out_store_ids      JSONB DEFAULT '[]',
    accepted_at              BIGINT,
    ws_channel_id            TEXT,
    estimated_delivery_minutes INT DEFAULT 30,
    delivered_at             BIGINT,
    failure_reason           TEXT,
    has_review               BOOLEAN DEFAULT false,
    is_direct_order          BOOLEAN DEFAULT false,
    broadcast_started_at     BIGINT,
    gstin                    TEXT  DEFAULT '',        -- optional GSTIN for B2B invoice
    donation_amount          FLOAT DEFAULT 0,         -- round-up donation added at checkout
    handling_charge          FLOAT DEFAULT 0,         -- flat handling fee shown on the bill
    delivery_instructions    JSONB DEFAULT '[]',      -- ["avoid_calling","no_bell",...]
    created_at               BIGINT DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_orders_customer     ON orders(customer_id);
CREATE INDEX IF NOT EXISTS idx_orders_store        ON orders(accepted_by_store_id);
CREATE INDEX IF NOT EXISTS idx_orders_status       ON orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_delivery_boy ON orders(assigned_delivery_boy_id);


-- ── delivery_boys ───────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS delivery_boys (
    id                   TEXT PRIMARY KEY,
    uid                  TEXT,
    store_id             TEXT,
    name                 TEXT,
    phone                TEXT,
    google_account_email TEXT,
    is_active            BOOLEAN DEFAULT true,
    current_order_id     TEXT,
    created_at           BIGINT DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_delivery_boys_store ON delivery_boys(store_id);
CREATE INDEX IF NOT EXISTS idx_delivery_boys_uid   ON delivery_boys(uid);
CREATE INDEX IF NOT EXISTS idx_delivery_boys_email ON delivery_boys(lower(google_account_email));


-- ── strike_logs ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS strike_logs (
    id             TEXT PRIMARY KEY,
    store_id       TEXT,
    order_id       TEXT,
    reason         TEXT,
    strike_number  INT,
    action_taken   TEXT,
    created_at     BIGINT DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_strikes_store ON strike_logs(store_id);


-- ── settlements ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS settlements (
    id                      TEXT PRIMARY KEY,
    store_id                TEXT,
    week_start              TEXT,               -- ISO date string "2026-01-06"
    week_end                TEXT,
    total_orders_delivered  INT DEFAULT 0,
    total_platform_fee_owed FLOAT DEFAULT 0,
    total_fee_paid          FLOAT DEFAULT 0,
    balance_due             FLOAT DEFAULT 0,
    status                  TEXT DEFAULT 'pending',
    is_overdue              BOOLEAN DEFAULT false,
    payment_records         JSONB DEFAULT '[]',
    created_at              BIGINT DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_settlements_store  ON settlements(store_id);
CREATE INDEX IF NOT EXISTS idx_settlements_status ON settlements(status);


-- ── admin_users ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS admin_users (
    uid        TEXT PRIMARY KEY,
    role       TEXT DEFAULT 'admin',
    created_at BIGINT DEFAULT 0
);


-- ── custom_item_requests (store asks admin to add a product) ────────────────
CREATE TABLE IF NOT EXISTS custom_item_requests (
    id               TEXT PRIMARY KEY,
    store_id         TEXT,
    requested_by_uid TEXT,
    name             TEXT,
    name_hindi       TEXT DEFAULT '',
    name_marathi     TEXT DEFAULT '',
    category         TEXT,
    unit             TEXT,
    price            FLOAT DEFAULT 0,
    notes            TEXT DEFAULT '',
    status           TEXT DEFAULT 'pending',
    created_at       BIGINT DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_custom_requests_store  ON custom_item_requests(store_id);
CREATE INDEX IF NOT EXISTS idx_custom_requests_status ON custom_item_requests(status);


-- ── reviews ─────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS reviews (
    id          TEXT PRIMARY KEY,
    order_id    TEXT,
    store_id    TEXT,
    customer_id TEXT,
    rating      INT,
    comment     TEXT DEFAULT '',
    created_at  BIGINT DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_reviews_store ON reviews(store_id);


-- ── notifications ───────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS notifications (
    id         TEXT PRIMARY KEY,
    uid        TEXT,               -- recipient user uid
    title      TEXT,
    body       TEXT,
    type       TEXT DEFAULT 'announcement',
    order_id   TEXT,
    is_read    BOOLEAN DEFAULT false,
    sender     TEXT DEFAULT 'system',
    created_at BIGINT DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_notifications_uid   ON notifications(uid);
CREATE INDEX IF NOT EXISTS idx_notifications_order ON notifications(order_id);


-- ── coming_soon_waitlist ("Notify me" demand for unserved areas) ────────────
CREATE TABLE IF NOT EXISTS coming_soon_waitlist (
    id          TEXT PRIMARY KEY,           -- uuid string (new_id())
    uid         TEXT NOT NULL,              -- Firebase UID of the requesting customer
    area        TEXT DEFAULT '',            -- reverse-geocoded area label (context only)
    lat         DOUBLE PRECISION,           -- the spot the customer wanted served
    lng         DOUBLE PRECISION,
    notified    BOOLEAN DEFAULT false,      -- set true once we ping them a store went live
    created_at  BIGINT DEFAULT 0,           -- epoch ms (last request)
    UNIQUE (uid, area)                      -- one active request per (customer, area)
);

CREATE INDEX IF NOT EXISTS idx_waitlist_area     ON coming_soon_waitlist(area);
CREATE INDEX IF NOT EXISTS idx_waitlist_notified ON coming_soon_waitlist(notified);


-- ── wishlist (saved-for-later, per customer) ────────────────────────────────
CREATE TABLE IF NOT EXISTS wishlist (
    uid        TEXT NOT NULL,            -- Firebase UID of the customer
    item_id    TEXT NOT NULL,            -- catalog_items.id
    created_at BIGINT DEFAULT 0,         -- epoch ms
    PRIMARY KEY (uid, item_id)
);

CREATE INDEX IF NOT EXISTS idx_wishlist_uid ON wishlist(uid);


-- ============================================================================
-- Safety net: if any of the above tables already existed from an OLDER schema
-- (before the marketplace migration), make sure the newer columns are present.
-- Harmless no-ops on a fresh DB created by this file.
-- ============================================================================
ALTER TABLE stores        ADD COLUMN IF NOT EXISTS store_type       TEXT DEFAULT 'grocery';
ALTER TABLE stores        ADD COLUMN IF NOT EXISTS self_delivery    BOOLEAN DEFAULT false;
ALTER TABLE orders        ADD COLUMN IF NOT EXISTS marketplace_type TEXT DEFAULT 'grocery';
ALTER TABLE catalog_items ADD COLUMN IF NOT EXISTS marketplace_type TEXT DEFAULT 'grocery';
ALTER TABLE catalog_items ADD COLUMN IF NOT EXISTS category_id      TEXT;
ALTER TABLE catalog_items ADD COLUMN IF NOT EXISTS subcategory_id   TEXT;
ALTER TABLE catalog_items ADD COLUMN IF NOT EXISTS brand            TEXT DEFAULT '';
ALTER TABLE catalog_items ADD COLUMN IF NOT EXISTS sku              TEXT DEFAULT '';
ALTER TABLE catalog_items ADD COLUMN IF NOT EXISTS description      TEXT DEFAULT '';
ALTER TABLE catalog_items ADD COLUMN IF NOT EXISTS mrp              FLOAT DEFAULT 0;
ALTER TABLE catalog_items ADD COLUMN IF NOT EXISTS discount_percent FLOAT DEFAULT 0;
ALTER TABLE catalog_items ADD COLUMN IF NOT EXISTS stock_quantity   INT DEFAULT 0;
ALTER TABLE catalog_items ADD COLUMN IF NOT EXISTS images           JSONB DEFAULT '[]';
ALTER TABLE catalog_items ADD COLUMN IF NOT EXISTS specs            JSONB DEFAULT '{}';
ALTER TABLE catalog_items ADD COLUMN IF NOT EXISTS group_id         TEXT;
ALTER TABLE catalog_items ADD COLUMN IF NOT EXISTS rating           FLOAT DEFAULT 0;
ALTER TABLE catalog_items ADD COLUMN IF NOT EXISTS rating_count     INT   DEFAULT 0;
ALTER TABLE orders        ADD COLUMN IF NOT EXISTS gstin                 TEXT  DEFAULT '';
ALTER TABLE orders        ADD COLUMN IF NOT EXISTS donation_amount       FLOAT DEFAULT 0;
ALTER TABLE orders        ADD COLUMN IF NOT EXISTS handling_charge       FLOAT DEFAULT 0;
ALTER TABLE orders        ADD COLUMN IF NOT EXISTS delivery_instructions JSONB DEFAULT '[]';
-- ============================================================================
-- END OF SCHEMA. Next: run 005_seed_marketplace.sql to populate the catalog,
-- then 007_variants_ratings_checkout.sql for demo ratings (or it's folded here).
-- ============================================================================
