-- DHAV: Initial PostgreSQL schema for Supabase
-- Run this once in: Supabase Dashboard → SQL Editor → New Query → Run
-- All tables use TEXT primary keys (UUID strings generated by the app via new_id())
-- Timestamps are stored as BIGINT milliseconds to match existing behavior

CREATE TABLE IF NOT EXISTS users (
    uid               TEXT PRIMARY KEY,            -- Firebase UID
    phone             TEXT,
    name              TEXT,
    email             TEXT,
    fcm_token         TEXT,
    address           JSONB,                       -- default delivery address
    saved_addresses   JSONB DEFAULT '[]',          -- list of saved address objects
    role              TEXT DEFAULT 'customer',     -- customer | store_owner | delivery | admin
    store_id          TEXT,                        -- set when role = store_owner
    language          TEXT DEFAULT 'en',
    is_active         BOOLEAN DEFAULT true,
    created_at        BIGINT DEFAULT 0             -- epoch ms
);

CREATE TABLE IF NOT EXISTS stores (
    id                   TEXT PRIMARY KEY,
    owner_uid            TEXT,
    owner_name           TEXT,
    shop_name            TEXT,
    name                 TEXT,                     -- alias used in admin onboard flow
    area                 TEXT,
    phone                TEXT,
    email                TEXT,
    address              TEXT,
    geohash6             TEXT,                     -- geohash precision-6 of store location
    location             JSONB,                    -- {lat, lng, geohash}
    is_open              BOOLEAN DEFAULT false,
    is_active            BOOLEAN DEFAULT true,
    is_verified          BOOLEAN DEFAULT false,
    is_suspended         BOOLEAN DEFAULT false,
    strike_count         INT DEFAULT 0,
    total_strikes        INT DEFAULT 0,
    suspension_end_date  BIGINT,
    available_item_ids   JSONB DEFAULT '[]',
    total_orders_accepted INT DEFAULT 0,
    total_orders_failed  INT DEFAULT 0,
    onboarded_by         TEXT,
    rating               FLOAT DEFAULT 0.0,
    fcm_token            TEXT,
    operating_hours      JSONB,
    image_url            TEXT DEFAULT '',
    onboarding_date      BIGINT,
    inventory            JSONB DEFAULT '{}',       -- {item_id: {qty, is_available}}
    updated_at           BIGINT,
    deleted_at           BIGINT,
    created_at           BIGINT DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_stores_geohash ON stores(geohash6);
CREATE INDEX IF NOT EXISTS idx_stores_owner   ON stores(owner_uid);
CREATE INDEX IF NOT EXISTS idx_stores_active  ON stores(is_active, is_open, is_verified);

CREATE TABLE IF NOT EXISTS catalog_items (
    id            TEXT PRIMARY KEY,
    name          TEXT NOT NULL,
    name_hindi    TEXT DEFAULT '',
    name_marathi  TEXT DEFAULT '',
    category      TEXT,
    price         FLOAT DEFAULT 0,
    unit          TEXT,
    is_active     BOOLEAN DEFAULT true,
    image_url     TEXT DEFAULT '',
    created_at    BIGINT DEFAULT 0,
    updated_at    BIGINT
);

CREATE INDEX IF NOT EXISTS idx_catalog_active   ON catalog_items(is_active);
CREATE INDEX IF NOT EXISTS idx_catalog_category ON catalog_items(category);

CREATE TABLE IF NOT EXISTS orders (
    id                       TEXT PRIMARY KEY,
    order_id                 TEXT,               -- same as id, for JSON response compatibility
    customer_id              TEXT,
    accepted_by_store_id     TEXT,
    assigned_delivery_boy_id TEXT,
    delivery_boy_name        TEXT,
    delivery_boy_phone       TEXT,
    status                   TEXT DEFAULT 'pending',
    items                    JSONB DEFAULT '[]',
    customer_address         JSONB,
    total_product_amount     FLOAT DEFAULT 0,
    delivery_fee             FLOAT DEFAULT 0,
    total_customer_amount    FLOAT DEFAULT 0,
    platform_fee_percentage  FLOAT DEFAULT 5.0,
    platform_fee_amount      FLOAT DEFAULT 0,
    platform_fee_settled     BOOLEAN DEFAULT false,
    payment_method           TEXT DEFAULT 'cod',
    broadcast_wave           INT DEFAULT 0,
    broadcast_radius_km      FLOAT DEFAULT 0,
    broadcast_store_ids      JSONB DEFAULT '[]',
    rejected_store_ids       JSONB DEFAULT '[]',
    timed_out_store_ids      JSONB DEFAULT '[]',
    accepted_at              BIGINT,
    ws_channel_id            TEXT,
    estimated_delivery_minutes INT DEFAULT 30,
    delivered_at             BIGINT,
    failure_reason           TEXT,
    has_review               BOOLEAN DEFAULT false,
    is_direct_order          BOOLEAN DEFAULT false,
    broadcast_started_at     BIGINT,
    created_at               BIGINT DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_orders_customer     ON orders(customer_id);
CREATE INDEX IF NOT EXISTS idx_orders_store        ON orders(accepted_by_store_id);
CREATE INDEX IF NOT EXISTS idx_orders_status       ON orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_delivery_boy ON orders(assigned_delivery_boy_id);

CREATE TABLE IF NOT EXISTS delivery_boys (
    id                   TEXT PRIMARY KEY,
    uid                  TEXT,
    store_id             TEXT,
    name                 TEXT,
    phone                TEXT,
    google_account_email TEXT,
    is_active            BOOLEAN DEFAULT true,
    current_order_id     TEXT,
    created_at           BIGINT DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_delivery_boys_store ON delivery_boys(store_id);
CREATE INDEX IF NOT EXISTS idx_delivery_boys_uid   ON delivery_boys(uid);
CREATE INDEX IF NOT EXISTS idx_delivery_boys_email ON delivery_boys(lower(google_account_email));

CREATE TABLE IF NOT EXISTS strike_logs (
    id             TEXT PRIMARY KEY,
    store_id       TEXT,
    order_id       TEXT,
    reason         TEXT,
    strike_number  INT,
    action_taken   TEXT,
    created_at     BIGINT DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_strikes_store ON strike_logs(store_id);

CREATE TABLE IF NOT EXISTS settlements (
    id                      TEXT PRIMARY KEY,
    store_id                TEXT,
    week_start              TEXT,               -- ISO date string "2026-01-06"
    week_end                TEXT,
    total_orders_delivered  INT DEFAULT 0,
    total_platform_fee_owed FLOAT DEFAULT 0,
    total_fee_paid          FLOAT DEFAULT 0,
    balance_due             FLOAT DEFAULT 0,
    status                  TEXT DEFAULT 'pending',
    is_overdue              BOOLEAN DEFAULT false,
    payment_records         JSONB DEFAULT '[]',
    created_at              BIGINT DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_settlements_store  ON settlements(store_id);
CREATE INDEX IF NOT EXISTS idx_settlements_status ON settlements(status);

CREATE TABLE IF NOT EXISTS admin_users (
    uid        TEXT PRIMARY KEY,
    role       TEXT DEFAULT 'admin',
    created_at BIGINT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS custom_item_requests (
    id               TEXT PRIMARY KEY,
    store_id         TEXT,
    requested_by_uid TEXT,
    name             TEXT,
    name_hindi       TEXT DEFAULT '',
    name_marathi     TEXT DEFAULT '',
    category         TEXT,
    unit             TEXT,
    price            FLOAT DEFAULT 0,
    notes            TEXT DEFAULT '',
    status           TEXT DEFAULT 'pending',
    created_at       BIGINT DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_custom_requests_store  ON custom_item_requests(store_id);
CREATE INDEX IF NOT EXISTS idx_custom_requests_status ON custom_item_requests(status);

CREATE TABLE IF NOT EXISTS reviews (
    id          TEXT PRIMARY KEY,
    order_id    TEXT,
    store_id    TEXT,
    customer_id TEXT,
    rating      INT,
    comment     TEXT DEFAULT '',
    created_at  BIGINT DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_reviews_store ON reviews(store_id);

CREATE TABLE IF NOT EXISTS notifications (
    id         TEXT PRIMARY KEY,
    uid        TEXT,               -- recipient user uid
    title      TEXT,
    body       TEXT,
    type       TEXT DEFAULT 'announcement',
    order_id   TEXT,
    is_read    BOOLEAN DEFAULT false,
    sender     TEXT DEFAULT 'system',
    created_at BIGINT DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_notifications_uid   ON notifications(uid);
CREATE INDEX IF NOT EXISTS idx_notifications_order ON notifications(order_id);
